### ISSUE TITLE
Add modules to the sidebar

### ISSUE THREAD

**Issue by B4nan** [tgreyuk/typedoc-plugin-markdown#186]
Modules are not part of the generated typedoc sidebar, which when using with docusaurus results in module detail pages not having the main sidebar rendered.

- module page: https://mikro-orm.io/docs/api/modules/core (left sidebar missing)
- enum page: https://mikro-orm.io/docs/api/enums/core.cascade (left sidebar rendered)

**Comment by tgreyuk** [comment]
Fixed in docusaurus-plugin-typedoc@0.8.0

**Comment by B4nan** [comment]
Looks like it is still the same (the typedoc sidebar now works fine, but modules are still not part of it).

**Comment by tgreyuk** [comment]
Yeah - on the 'next' version the modules are listed in the sidebar but now we do not have the 'Table of Content' / index item. https://mikro-orm.io/docs/next/api/modules/core . Sorry - will fix that .

**Comment by tgreyuk** [comment]
Please try:
 - docusaurus-plugin-typedoc@0.8.1
 - typedoc-plugin-markdown@3.4.4
