### ISSUE TITLE
IndexPageTitle not working as expected

### ISSUE THREAD

**Issue by osama-salman99** [tgreyuk/typedoc-plugin-markdown#480]
I know 4.0.0-next is not a stable version, but in v4.0.0-next.18 (and later) the IndexPageTitle does not work as expected as it always renders "API" instead of the project name or the value provided.

**Comment by tgreyuk** [comment]
Hi. Yes sorry - fixed in typedoc-plugin-markdown%404.0.0-next.23 .

**Comment by osama-salman99** [comment]
That is great! Thank you so much.

There's still one small issue that it still does not default to the `"{projectName}"` when left empty as documented [here](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/typedoc-plugin-markdown%404.0.0-next.23/packages/typedoc-plugin-markdown/docs/guides/options.md#--indexpagetitle).

**Comment by tgreyuk** [comment]
> There's still one small issue that it still does not default to the "{projectName}" when left empty as documented.

Thanks for pointing this out. Also fixed.
